apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: william861227/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
          - containerPort: 3111
        livenessProbe:
          httpGet:
            path: {{ .Values.image.livenessProbe.httpGet.path }}
            port: {{ .Values.image.livenessProbe.httpGet.port }}
        readinessProbe:
          httpGet:
            path: {{ .Values.image.readinessProbe.httpGet.path }}
            port: {{ .Values.image.readinessProbe.httpGet.port }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

