apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-staging
  namespace: staging
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values-staging
    path: helm
    repoURL: https://github.com/cloud-native-workshops/tech-trends-p1
    targetRevision: HEAD
  syncPolicy: {}




